### ISSUE TITLE
Question: How’s this different from 101?

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/1-liners#4]
@stoeffel seems quite similar in scope. Why not integrate `head` and `tail` into *101*?

**Comment by tomekwi** [comment]
Though I must admit that the source looks delicious :) :honey_pot:

**Comment by stoeffel** [comment]
@tomekwi Checkout the discussion in https://github.com/tjmehta/101/pull/89

This oneliners are sometimes overkill for 101. 1-liners should contain even simpler functions and functionality you gain by transpiling es6 (i.e. `export default (fn) => (...rest) => fn(rest);`)
I want to provide shorthands and convenience functions to stuff that could easily be done in vanilla js, but are nice with some sugar (honey).
This lib could be seen as an extension for 101 rather than a replacement. And it's fun to do stuff in one line of code :smile:

**Comment by stoeffel** [comment]
@tjmehta any thoughts from you about this? I don't want this to interfere with 101. I will try to keep overlappings as minimal as possible.

**Comment by tomekwi** [comment]
@stoeffel thanks for the heads up! I’m *ganz gespannt* :)

**Comment by stoeffel** [comment]
@tomekwi Kein Problem. PRs sind sehr willkommen :smiley:

**Comment by tomekwi** [comment]
:)

I’m totally tied up at the moment :/

But I keep trying to squeeze some open-source goodness into the work I’m into at the moment. So I’ll chime in when I have an idea.

**Comment by stoeffel** [comment]
@tomekwi Thanks for the help! Feel free to implement anything from the todolist or what ever idea you may have.
